apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nahidh597/blog
      context: blog
      docker:
        dockerfile: Dockerfile
        sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: nahidh597/comment-service
      context: comments-service
      docker:
        dockerfile: Dockerfile
        sync:
        manual:
          - src: '*.js'
            dest: .
    - image: nahidh597/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
        sync:
        manual:
          - src: '*.js'
            dest: .
    - image: nahidh597/moduration-service
      context: moduration
      docker:
        dockerfile: Dockerfile
        sync:
        manual:
          - src: '*.js'
            dest: .
    - image: nahidh597/post-service
      context: post-service
      docker:
        dockerfile: Dockerfile
        sync:
        manual:
          - src: '*.js'
            dest: .
    - image: nahidh597/query-service
      context: query-service
      docker:
        dockerfile: Dockerfile
        sync:
        manual:
          - src: '*.js'
            dest: .