apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: blog-microservice
build:
  artifacts:
  - image: nahidh597/blog
    context: blog
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: nahidh597/comment-service
    context: comments-service
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: nahidh597/event-bus
    context: event-bus
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: nahidh597/moduration-service
    context: moduration
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: nahidh597/post-service
    context: post-service
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: nahidh597/query-service
    context: query-service
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - infra/k8s/blog-depl.yaml
    - infra/k8s/comment-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moduration-depl.yaml
    - infra/k8s/post-depl.yaml
    - infra/k8s/post-srv.yaml
    - infra/k8s/query-depl.yaml
